/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "https://gszojnzfjgywuonzvhiz.supabase.co"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzem9qbnpmamd5d3Vvbnp2aGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMzM3MTcsImV4cCI6MjA3NjcwOTcxN30.MYDfetERKvpnotcxn7HPD1J-I-Fq87xWYt_CZ4tdgII"